### ISSUE TITLE
Missing devDependency tslib 

### ISSUE THREAD

**Issue by michielbdejong** [NoelDeMartin/utils#2]
```
michiel-2:utils michiel$ npm run build:js

> @noeldemartin/utils@0.4.0 build:js /Users/michiel/gh/NoelDeMartin/utils
> noeldemartin-build-javascript


src/main.ts → dist...
[!] (plugin typescript) Error: @rollup/plugin-typescript: Could not find module 'tslib', which is required by this plugin. Is it installed?
Error: @rollup/plugin-typescript: Could not find module 'tslib', which is required by this plugin. Is it installed?
    at error (/Users/michiel/gh/NoelDeMartin/utils/node_modules/rollup/dist/shared/rollup.js:158:30)
    at throwPluginError (/Users/michiel/gh/NoelDeMartin/utils/node_modules/rollup/dist/shared/rollup.js:21769:12)
    at Object.error (/Users/michiel/gh/NoelDeMartin/utils/node_modules/rollup/dist/shared/rollup.js:22472:20)
    at preflight (/Users/michiel/gh/NoelDeMartin/utils/node_modules/@rollup/plugin-typescript/dist/index.js:495:17)
    at Object.buildStart (/Users/michiel/gh/NoelDeMartin/utils/node_modules/@rollup/plugin-typescript/dist/index.js:736:13)
    at /Users/michiel/gh/NoelDeMartin/utils/node_modules/rollup/dist/shared/rollup.js:22681:25
    at async Promise.all (index 0)
    at rollupInternal (/Users/michiel/gh/NoelDeMartin/utils/node_modules/rollup/dist/shared/rollup.js:23397:9)
    at build (/Users/michiel/gh/NoelDeMartin/utils/node_modules/rollup/dist/bin/rollup:1547:20)
    at runRollup (/Users/michiel/gh/NoelDeMartin/utils/node_modules/rollup/dist/bin/rollup:1731:21)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @noeldemartin/utils@0.4.0 build:js: `noeldemartin-build-javascript`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @noeldemartin/utils@0.4.0 build:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michiel/.npm/_logs/2023-11-20T09_54_33_178Z-debug.log
```

**Comment by NoelDeMartin** [comment]
Thanks for opening the issue, I've updated the `@noeldemartin/scripts` dependency which now declares `tslib` as a dependency so it should be fixed.
